name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Publish webextension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Upload to Chrome Webstore
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: dist.zip
          extension-id: hogefuga(extension id)
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
      - name: Upload to Github Release
        uses: softprops/action-gh-release@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist.zip
